.\" Debian manpage for the application
.TH NETSPEED 1 "October 2023"
.SH NAME
netspeed \- a tool to view network speeds and other stats in a GUI
.SH SYNOPSIS
.B netspeed
[
--help
]
.SH DESCRIPTION
.PP
The
.B netspeed
command is a graphical user interface (GUI) tool for viewing network speeds.
.PP
It displays real-time network usage statistics for the all network interfaces.
.SH BUGS
Report bugs to <https://github.com/agrawal-d/netspeed>